### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Jessie93** [ladykays/wax-and-wicks#2]

**Comment by ladykays** [comment]
**User Story**

As a user, when I visit the website, I want to:

- see a well laid out footer on all pages
- see links to the different GitHub pages of the collaborators
- see a copyright text
- be able to click on each of the links and the page to the link is opened on a new browser window

**Acceptance Criteria**

It is done when I visit the website I:

- [x] see a well laid out footer on all pages
- [x] see links to the different GitHub pages of the collaborators
- [x] see a copyright text
- [x] am able to click on each of the links and the page to the link is opened on a new browser window
