### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by Jessie93** [ladykays/wax-and-wicks#3]
Create a navBar that is horizontal and follows the design within the Figma file. 
- Add functionality to the navBar using JavaScript 
- Test and make sure the navbar works on different size screens

**Comment by ladykays** [comment]
**User Story**

As a user, when I visit the website, I want to: 

- see a well laid out navigation bar on all pages
- see links to the homepage, shop, contact and basket pages
- see a responsive nav bar that looks good on all different screen sizes
- be able to click on each of the links and the page is displayed

**Acceptance Criteria**

It is done when I visit the website: 

- [ ] I see a well laid out navigation bar on all pages
- [ ]  I see links to the homepage, shop, contact and basket pages
- [ ]  I see a responsive nav bar that looks good on all different screen sizes
- [ ]  and click any of the links, the page is displayed

**Comment by ffionerin** [comment]
User Story:
As a user, I want to easily navigate the Wax and Wicks website and access different sections of the site from the navbar.

Acceptance Criteria:

The navbar should be visible on all pages of the website.
The navbar should include links to the Home, Shop, Contact and Basket pages.
The links in the navbar should be styled to be easily distinguishable from other text on the page.
The current page should be visually differentiated in the navbar, to indicate which page the user is currently viewing.
